---
name: aurora-dx-1password-and-wezterm
# description will be included in the image's metadata
description: Aurora DX with 1password and wezterm

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx
image-version: stable
# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: fonts
    fonts:
      nerd-fonts:
        - Hack

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: bling
    install:
      - 1password

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/wezfurlong/wezterm-nightly/repo/fedora-%OS_VERSION%/wezfurlong-wezterm-nightly-fedora-%OS_VERSION%.repo
      - https://download.opensuse.org/repositories/home:paul4us/Fedora_%OS_VERSION%/home:paul4us.repo

    install:
      - autoconf
      - gcc
      - patch
      - make
      - bzip2
      - openssl-devel
      - libyaml-devel
      - libffi-devel
      - readline-devel
      - gdbm-devel
      - ncurses-devel
      - perl-FindBin # Because of OpenSSL!
      # dependencies for panel colorizer c++ plugin https://github.com/luisbocanegra/plasma-panel-colorizer
      - git
      - gcc-c++
      - cmake
      - extra-cmake-modules
      - libplasma-devel
      - spectacle
      - python3
      - python3-dbus
      - python3-gobject

      # Necessary for Quality of Life
      - wezterm
      - klassy


  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
#    system:
#      # If no repo information is specified, Flathub will be used by default
#      install:
#        -
#      remove:
#        -
    user: {} # Also add Flathub user repo, but no user package

#  - type: script
#    snippets:
#      - echo "🔍 Listing files under /usr/etc..."
#      - find /usr/etc || echo "/usr/etc not found"
#      - echo "📁 Listing everything under /usr just in case:"
#      - find /usr | grep etc || true

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
